apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: host
  displayName: Host
  icon: /icons/sources/host.svg
  description: Collect metrics from the collector's host.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: metric_filtering
      type: metrics
      default:
        - system.disk.io
        - system.disk.io_time
        - system.disk.merged
        - system.disk.operation_time
        - system.disk.operations
        - system.disk.pending_operations
        - system.disk.weighted_io_time
        - system.processes.count
        - system.processes.created
        - system.cpu.time
        - system.cpu.utilization
      options:
        metricCategories:
          - label: Filesystem Metrics
            metrics:
              - name: system.filesystem.inodes.usage
              - name: system.filesystem.usage
              - name: system.filesystem.utilization
          - label: Memory Metrics
            metrics:
              - name: system.memory.usage
              - name: system.memory.utilization
          - label: Network Metrics
            metrics:
              - name: system.network.connections
              - name: system.network.conntrack.count
              - name: system.network.conntrack.max
              - name: system.network.dropped
              - name: system.network.errors
              - name: system.network.io
              - name: system.network.packets
          - label: Paging Metrics
            metrics:
              - name: system.paging.faults
              - name: system.paging.operations
              - name: system.paging.operations.page_in
              - name: system.paging.operations.page_out
              - name: system.paging.usage
              - name: system.paging.utilization
          - label: Load Metrics
            column: 1
            metrics:
              - name: system.cpu.load_average.15m
              - name: system.cpu.load_average.1m
              - name: system.cpu.load_average.5m
          - label: CPU Metrics
            column: 1
            metrics:
              - name: system.cpu.time
              - name: system.cpu.utilization
          - label: Disk Metrics
            column: 1
            metrics:
              - name: system.disk.io
              - name: system.disk.io_time
              - name: system.disk.merged
              - name: system.disk.operation_time
              - name: system.disk.operations
              - name: system.disk.pending_operations
              - name: system.disk.weighted_io_time
          - label: Processes Metrics
            column: 1
            metrics:
              - name: system.processes.count
              - name: system.processes.created

    # Process metrics w/ filtering
    - name: enable_process
      label: Process Metrics
      description: Enable to collect process metrics. Compatible with Linux and Windows. The collector must be running as root (Linux) and Administrator (Windows).
      type: bool
      default: true
      options:
        sectionHeader: true

    - name: process_metrics_filtering
      type: metrics
      options:
        metricCategories:
          - label: Process Metrics
            metrics:
              - name: process.cpu.time
              - name: process.disk.io
              - name: process.memory.physical_usage
              - name: process.memory.virtual_usage
      default: []
      relevantIf:
        - name: enable_process
          operator: equals
          value: true

    - name: enable_process_filter
      label: Process Name Filtering
      description: Enable to configure filtering for process metrics.
      type: bool
      default: false
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_process
          operator: equals
          value: true

    - name: process_include
      label: Process Include Filter
      description: List of processes to include for metric collection. Defaults to all processes.
      type: strings
      default: []
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

    - name: process_exclude
      label: Process Exclude Filter
      description: List of processes to exclude from metric collection.
      type: strings
      default: []
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

    - name: process_filter_match_strategy
      label: Process Filter Match Type
      description: Strategy for matching process names.
      type: enum
      default: regexp
      validValues:
        - regexp
        - strict
      relevantIf:
        - name: enable_process_filter
          operator: equals
          value: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true

  metrics:
    receivers: |
      - hostmetrics:
          collection_interval: {{ .collection_interval }}s
          scrapers:
          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Load Metrics" }}
            load:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Load Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Filesystem Metrics" }}
            filesystem:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Filesystem Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}


          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Memory Metrics" }}
            memory:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Memory Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Network Metrics" }}
            network:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Network Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Paging Metrics" }}
            paging:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Paging Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Disk Metrics" }}
            disk:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Disk Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}


          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "CPU Metrics" }}
            cpu:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "CPU Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

          {{ if bpHasCategoryMetricsEnabled .metric_filtering "metric_filtering" "Processes Metrics" }}
            processes:
              metrics:
                {{ range $m := bpDisabledCategoryMetrics .metric_filtering "metric_filtering" "Processes Metrics" }}
                {{ $m }}:
                  enabled: false
                {{ end }}
          {{ end }}

            {{ if .enable_process }}
            process:
              {{ if .process_metrics_filtering }}
              metrics:
                {{ range $m := .process_metrics_filtering }}
                {{ $m }}:
                  enabled: false
                {{ end }}
              {{ end }}

              {{ if .enable_process_filter }}
              include:
                names:
                {{ range $p := .process_include }}
                - '{{ $p }}'
                {{ end }}
                match_type: {{ .process_filter_match_strategy }}
              exclude:
                names:
                {{ range $p := .process_exclude }}
                - '{{ $p }}'
                {{ end }}
                match_type: {{ .process_filter_match_strategy }}
              {{ end }}
              mute_process_name_error: true
            {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
