apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: oracledb
  displayName: Oracle Database
  icon: /icons/sources/oracledb.svg
  description: Collect metrics and logs from Oracle Database.
spec:
  version: 0.1.0
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: enable_metrics
      label: Enable Metrics
      description: Enable to collect metrics.
      type: bool
      default: true

    - name: host
      label: Host
      description: Host to scrape metrics from.
      type: string
      default: localhost
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: port
      label: Port
      description: Port of host to scrape metrics from.
      type: int
      default: 1521
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: username
      label: Username
      description: Database user to run metric queries with.
      type: string
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: password
      label: Password
      description: Password for user.
      type: string
      default: ""
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: database_identification
      label: Database Identification
      description: Use Site Identifier and/or Service Name to identify the database to scrape.
      type: enums
      validValues:
        - "SID"
        - "Service Name"
      default: ["SID"]
      options:
        gridColumns: 12
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: sid
      label: SID
      description: OracleDB Site Identifier.
      type: string
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
        - name: database_identification
          operator: containsAny
          value: ["SID"]

    - name: service_name
      label: Service Name
      description: OracleDB Service Name.
      type: string
      required: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true
        - name: database_identification
          operator: containsAny
          value: ["Service Name"]

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: wallet
      label: Wallet
      description: OracleDB Wallet file location (must be URL encoded).
      type: string
      default: ""
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: enable_logs
      label: Enable Logs
      description: Enable to collect logs.
      type: bool
      default: true

    - name: enable_audit_log
      label: Audit Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: audit_log_path
      label: Audit Log Path(s)
      description: File paths to audit logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/u01/app/oracle/product/*/dbhome_1/admin/*/adump/*.aud"
      required: true
      relevantIf:
        - name: enable_audit_log
          operator: equals
          value: true
        - name: enable_logs
          operator: equals
          value: true

    - name: enable_alert_log
      label: Alert Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: alert_log_path
      label: Alert Log Path(s)
      description: File paths to alert logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/u01/app/oracle/product/*/dbhome_1/diag/rdbms/*/*/trace/alert_*.log"
      required: true
      relevantIf:
        - name: enable_alert_log
          operator: equals
          value: true
        - name: enable_logs
          operator: equals
          value: true

    - name: enable_listener_log
      label: Listener Logs
      type: bool
      default: true
      options:
        sectionHeader: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: listener_log_path
      label: Listener Log Path(s)
      description: File paths to alert logs.
      type: strings
      options:
        gridColumns: 12
      default:
        - "/u01/app/oracle/product/*/dbhome_1/diag/tnslsnr/*/listener/alert/log.xml"
      required: true
      relevantIf:
        - name: enable_listener_log
          operator: equals
          value: true
        - name: enable_logs
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin/oracledb_logs:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/oracle_database_logs.yaml
          parameters:
            start_at: {{ .start_at }}

            enable_audit_log: {{ .enable_audit_log}}
            {{ if .enable_audit_log }}
            audit_log_path:
              {{ range $fp := .audit_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}

            enable_alert_log: {{ .enable_alert_log}}
            {{ if .enable_alert_log }}
            alert_log_path:
              {{ range $fp := .alert_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}

            enable_listener_log: {{ .enable_listener_log}}
            {{ if .enable_listener_log }}
            listener_log_path:
              {{ range $fp := .listener_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
      {{ end }}

    processors: |
      {{ if .enable_logs }}
      - resourcedetection/logs:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - plugin/oracledb_metrics:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/oracledb_metrics.yaml
          parameters:
            endpoint: {{ .host }}:{{ .port }}
            username: {{ .username }}
            password: '{{ .password }}'
            {{ if and (has "SID" .database_identification) .sid }}
            sid: {{ .sid }}
            {{ end }}
            {{ if and (has "Service Name" .database_identification) .service_name }}
            service_name: {{ .service_name }}
            {{ end }}
            {{ if .wallet }}
            wallet: {{ .wallet }}
            {{ end }}
            scrape_interval: {{ .collection_interval }}s
      {{ end }}

    processors: |
      {{ if .enable_metrics }}
      - resourcedetection/metrics:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
      {{ end }}
