apiVersion: bindplane.observiq.com/v1
kind: DestinationType
metadata:
  name: custom
  displayName: Custom
  description: Insert a custom OpenTelemetry exporter configuration.
  icon: /icons/destinations/custom.svg

spec:
  version: 0.0.1
  parameters:
    - name: telemetry_types
      label: Telemetry Types
      type: enums
      description: "Select which types of telemetry the exporter supports."
      validValues: ["Metrics", "Logs", "Traces"]
      default: []

    - name: configuration
      label: Configuration
      description: Enter any supported OpenTelemetry exporter and the YAML will be inserted into the configuration.
      type: yaml
      options:
        gridColumns: 12
      required: true
      documentation:
        - text: Exporter Syntax
          url: https://github.com/observIQ/observiq-otel-collector/blob/main/docs/exporters.md

  logs:
    exporters: |
      {{ if has "Logs" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}

  metrics:
    exporters: |
      {{ if has "Metrics" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}

  traces:
    exporters: |
      {{ if has "Traces" .telemetry_types }}
      - {{ .configuration | nindent 2 }}
      {{ end }}
